name: .NET WinForms Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Install the .NET workload
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore the application dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the application
    - name: Build the app
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    # Upload the compiled application so you can download the .exe from GitHub
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: QwertySubstitutionCipher-App
        # This grabs everything in the output folder. If you are using .NET 6/7, change net8.0-windows below.
        path: QwertySubstitutionCipher/bin/${{ matrix.configuration }}/net8.0-windows/
